import { Composition } from "remotion";
import { MyScene } from "./Animation";
import data from "../image-list.json"; // Generated by get-images.js

export const RemotionRoot = () => {
  return (
    <>
      <Composition
        id="MyVideo"
        component={MyScene}
        durationInFrames={300} // 10 seconds at 30fps
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{
          images: data
        }}
      />
    </>
  );
};
