name: Generate Amazon & Audible Affiliate Links

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"  # Optional: runs daily at 00:00 UTC

jobs:
  generate-links:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API: ${{ secrets.GOOGLE_API }}
      GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
      ASSOCIATE_ID: bookslibrar08-20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run comp3.py
        run: python REDDIT/CODE/COMPANY_BIO/comp3.py
