
name: Generate Amazon & Audible Links

on:
  workflow_dispatch:       # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"   # Optional: runs daily at 00:00 UTC

jobs:
  generate-links:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API: ${{ secrets.GOOGLE_API }}
      GOOGLE_CX: ${{ secrets.GOOGLE_CX }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # Allows git push with GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run comp3.py
        run: python REDDIT/CODE/COMPANY_BIO/comp3.py

      - name: Commit updated links
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add REDDIT/THEMES/Company\ bio/BOOKS/LINKS/
          git diff --cached --quiet || git commit -m "Update Amazon & Audible links"
          git push
