
name: Generate & Commit Affiliate Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # optional: daily at 00:00 UTC

jobs:
  generate-aff-links:
    runs-on: ubuntu-latest

    env:
      ASSOCIATE_ID: bookslibrar08-20

    steps:
      - name: Checkout repository with write permissions
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ensures push permission
          persist-credentials: true            # persist token for git commands

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run comp4.py to generate affiliate links
        run: python REDDIT/CODE/COMPANY_BIO/comp4.py

      - name: Commit and push affiliate links
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add REDDIT/THEMES/Company\ bio/BOOKS/AFF/amazon.txt
          git add REDDIT/THEMES/Company\ bio/BOOKS/AFF/audible.txt
          git commit -m "Update affiliate links" || echo "No changes to commit"
          git push origin main
