
name: FastDepth Depth Map

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Allows manual trigger

jobs:
  run-fastdepth:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision matplotlib opencv-python

    # 4. Run the FastDepth script
    - name: Run FastDepth
      run: |
        python MANIM/Fast_depth.py

    # 5. Upload output as artifact
    - name: Upload Depth Map Artifact
      uses: actions/upload-artifact@v4
      with:
        name: depth-map
        path: assets/images/amazon_box_depth.png
