
name: Render Video with Revideo

on: workflow_dispatch:

jobs: render: runs-on: ubuntu-latest steps: - name: Checkout repo uses: actions/checkout@v3

- name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install Revideo
    run: |
      npm init -y
      npm install @revideo/2d @revideo/core @revideo/cli

  - name: Create video
    run: |
      npx revideo render src/index.ts --out output.mp4

  - name: Upload video artifact
    uses: actions/upload-artifact@v4
    with:
      name: revideo-output
      path: output.mp4

