
name: Render Revideo Animation

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message text'
        required: false
        default: 'Default Message'

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      MESSAGE: ${{ github.event.inputs.message }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Render animation
        run: npm run render

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: output_video
          path: output.mp4
