
name: Render Revideo Animation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Revideo
        run: |
          npm init -y
          npm install @revideo/core @revideo/2d

      - name: Render
        run: npx revideo render coolText.tsx --out=output.mp4

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.mp4
