
name: 🔁 Smart Link Processor

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "link-processing"
  cancel-in-progress: true

jobs:
  process-links:
    runs-on: ubuntu-latest
    name: 🧠 Process Smart Links Automatically

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Run Python script in verbose mode
        run: |
          export PYTHONUNBUFFERED=1
          pip install --no-cache-dir --progress-bar=off google-genai
          python -u Unusual_links_relevant.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
          GEMINI_API2: ${{ secrets.GEMINI_API2 }}
          GEMINI_API3: ${{ secrets.GEMINI_API3 }}
          GEMINI_API4: ${{ secrets.GEMINI_API4 }}
          GEMINI_API5: ${{ secrets.GEMINI_API5 }}

      - name: ✅ Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add Unuusual_memory/Relevant_links/

          if git diff --cached --quiet; then
            echo "🟡 No changes to commit."
          else
            git commit -m "🤖 Update relevant links via Smart Link Processor"
            git push
            echo "✅ Changes committed and pushed."
          fi
