
name: Run Unusual Description

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  unusual-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required Python packages
        run: |
          pip install --upgrade pip
          pip install google-api-python-client

      - name: Run Unusual_descreption.py
        env:
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
        run: python Unusual_descreption.py

      - name: Upload video info files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-descriptions
          path: Vid/
