
name: 🔁 Smart Link Processor with Ratings

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "link-processing-rating"
  cancel-in-progress: true

jobs:
  process-links-with-rating:
    runs-on: ubuntu-latest
    name: 🧠 Process Smart Links with Rating Automatically

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Run Rating Python Script in Verbose Mode
        run: |
          export PYTHONUNBUFFERED=1
          pip install --no-cache-dir --progress-bar=off google-genai
          python -u Unususal_5rating.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
          GEMINI_API2: ${{ secrets.GEMINI_API2 }}
          GEMINI_API3: ${{ secrets.GEMINI_API3 }}
          GEMINI_API4: ${{ secrets.GEMINI_API4 }}
          GEMINI_API5: ${{ secrets.GEMINI_API5 }}

      - name: ✅ Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add Unuusual_memory/RATING/

          if git diff --cached --quiet; then
            echo "🟡 No changes to commit."
          else
            git commit -m "🤖 Update ratings via Smart Link Processor with Rating"
            git push
            echo "✅ Changes committed and pushed."
          fi
