
name: 🔁 Smart Product Script Generator

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "product-script-generator"
  cancel-in-progress: true

jobs:
  generate-product-scripts:
    runs-on: ubuntu-latest
    name: 🧠 Generate Product Scripts from Descriptions

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Run Python script for Product Script Generation
        run: |
          export PYTHONUNBUFFERED=1
          pip install --no-cache-dir --progress-bar=off google-genai
          python -u Unusual_script.py
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
          GEMINI_API2: ${{ secrets.GEMINI_API2 }}
          GEMINI_API3: ${{ secrets.GEMINI_API3 }}
          GEMINI_API4: ${{ secrets.GEMINI_API4 }}
          GEMINI_API5: ${{ secrets.GEMINI_API5 }}

      - name: ✅ Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git add Unuusual_memory/SCRIPT/

          if git diff --cached --quiet; then
            echo "🟡 No changes to commit."
          else
            git commit -m "🤖 Update product scripts via Product Script Generator"
            git push
            echo "✅ Changes committed and pushed."
          fi
